#!/bin/bash

. ~/.genpatchesrc

name="${ECHANGELOG_USER%<*}"
email="${ECHANGELOG_USER#*<}"
email="${email%>}"

cd ${WEB_LOCAL}
perl email-announcement.pl $1 ${KERNEL_NAME} |
	${SENDMAIL} -F \"${name}\" -f \"${email}\" gentoo-kernel@lists.gentoo.org


