#!/bin/bash

if [[ ${#@} == 0 ]] ; then
	echo ">>> USAGE: gpdorelease <branch-minor>"
	echo "This will expand to ${LOCAL_PATCHES_TRUNK}/2.6.<branch-minor>"
	exit -1
fi

if [[ ${1} == "--config" ]] ; then
	echo "Sourcing ${2} instead of ~/.genpatchesrc"
	source ${2}
	shift 2
else
	echo "Using default config at ~/.genpatchesrc"
	source ~/.genpatchesrc
fi

BRANCH="2.6.$1"

if [[ $(svn status ${LOCAL_PATCHES_TRUNK} | wc -l) != "0" ]] ; then
	echo ">>> ERROR: There are uncommited changes in ${LOCAL_PATCHES_TRUNK}"
	exit -1
fi

EXISTING_TAGS="$(svn ls ${REMOTE_TAGS})"

lastver=0
for i in $EXISTING_TAGS ; do
	tag="${i%/}"
	if [[ ${tag/-*} == $BRANCH && ${tag#*-} -gt $lastver ]] ; then
		lastrelease="${tag}"
		lastver="${tag#*-}"
	fi
done

if [[ -z $lastrelease ]] ; then
	newrel="1"
else
	newrel="${lastrelease#${BRANCH}-}"
	(( newrel++ ))
fi

newfullver="${BRANCH}-${newrel}"

echo "I will now:"
echo "1. Tag the ${BRANCH} branch as ${newfullver} (immediate commit)"
echo "2. Produce genpatches-${newfullver} tarballs"
echo "3. Upload tarballs to distfiles-local"
echo "4. (Optionally) create and upload website"
echo "5. (Optionally) send a release announcement to gentoo-kernel"
echo
echo "Make sure everything is already committed and ready to roll."
echo "Press enter to continue."

read

svn copy ${REMOTE_TRUNK}/${BRANCH} ${REMOTE_TAGS}/${newfullver} -m "${newfullver} release"

file_base="/tmp/${TARBALL_BASENAME}-$newfullver.base.tar.bz2"
file_extras="/tmp/${TARBALL_BASENAME}-$newfullver.extras.tar.bz2"
dir="${BRANCH}"
cd ${LOCAL_PATCHES_TRUNK}

if [[ "${WE_WANT}" == "base extras" ]] ; then
	[ -n "$(find ${dir}/[012]* 2>/dev/null)" ] && tar -cvjf ${file_base} ${dir}/[012]*
	[ -n "$(find ${dir}/[34]* 2>/dev/null)" ] &&  tar -cvjf ${file_extras} ${dir}/[34]*
elif [[ "${WE_WANT}" == "extras" ]] ; then
	[ -n "$(find ${dir}/[34]* 2>/dev/null)" ] &&  tar -cvjf ${file_extras} ${dir}/[34]*
fi

scp /tmp/${TARBALL_BASENAME}-$newfullver.* ${USERNAME}@dev.gentoo.org:/space/distfiles-local

if [[ ${DO_WEBSITE} == "yes" ]] ; then
	mv ${file_base} ${file_extras} ${WEB_LOCAL}/tarballs/
	gpdoweb
fi

[[ ${DO_EMAIL_ANNOUNCEMENT} == "yes" ]] && gpdoemail $newfullver $KERNEL_NAME
